/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as CategoriesRouteImport } from './routes/categories';
import { Route as BlogRouteImport } from './routes/blog';
import { Route as BecomeContributorRouteImport } from './routes/become-contributor';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminIndexRouteImport } from './routes/admin.index';
import { Route as DashboardNewRouteImport } from './routes/dashboard.new';
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug';
import { Route as BlogSlugRouteImport } from './routes/blog.$slug';
import { Route as AdminReviewRouteImport } from './routes/admin.review';
import { Route as AdminPostsRouteImport } from './routes/admin.posts';
import { Route as AdminContributorsRouteImport } from './routes/admin.contributors';
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories';
import { Route as DashboardEditIdRouteImport } from './routes/dashboard.edit.$id';
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
});
const CategoriesRoute = CategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => rootRouteImport,
});
const BlogRoute = BlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => rootRouteImport,
});
const BecomeContributorRoute = BecomeContributorRouteImport.update({
    id: '/become-contributor',
    path: '/become-contributor',
    getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminRoute,
});
const DashboardNewRoute = DashboardNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardRoute,
});
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => CategoriesRoute,
});
const BlogSlugRoute = BlogSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => BlogRoute,
});
const AdminReviewRoute = AdminReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AdminRoute,
});
const AdminPostsRoute = AdminPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AdminRoute,
});
const AdminContributorsRoute = AdminContributorsRouteImport.update({
    id: '/contributors',
    path: '/contributors',
    getParentRoute: () => AdminRoute,
});
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminRoute,
});
const DashboardEditIdRoute = DashboardEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => DashboardRoute,
});
const AdminRouteChildren = {
    AdminCategoriesRoute: AdminCategoriesRoute,
    AdminContributorsRoute: AdminContributorsRoute,
    AdminPostsRoute: AdminPostsRoute,
    AdminReviewRoute: AdminReviewRoute,
    AdminIndexRoute: AdminIndexRoute,
};
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);
const BlogRouteChildren = {
    BlogSlugRoute: BlogSlugRoute,
};
const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren);
const CategoriesRouteChildren = {
    CategoriesSlugRoute: CategoriesSlugRoute,
};
const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(CategoriesRouteChildren);
const DashboardRouteChildren = {
    DashboardNewRoute: DashboardNewRoute,
    DashboardEditIdRoute: DashboardEditIdRoute,
};
const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    AdminRoute: AdminRouteWithChildren,
    BecomeContributorRoute: BecomeContributorRoute,
    BlogRoute: BlogRouteWithChildren,
    CategoriesRoute: CategoriesRouteWithChildren,
    ContactRoute: ContactRoute,
    DashboardRoute: DashboardRouteWithChildren,
    LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
