/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BecomeContributorRouteImport } from './routes/become-contributor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminContributorsRouteImport } from './routes/admin.contributors'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as DashboardEditIdRouteImport } from './routes/dashboard.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeContributorRoute = BecomeContributorRouteImport.update({
  id: '/become-contributor',
  path: '/become-contributor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/dashboard/new',
  path: '/dashboard/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContributorsRoute = AdminContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardEditIdRoute = DashboardEditIdRouteImport.update({
  id: '/dashboard/edit/$id',
  path: '/dashboard/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-contributor': typeof BecomeContributorRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contributors': typeof AdminContributorsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/review': typeof AdminReviewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-contributor': typeof BecomeContributorRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contributors': typeof AdminContributorsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/review': typeof AdminReviewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-contributor': typeof BecomeContributorRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contributors': typeof AdminContributorsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/review': typeof AdminReviewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/edit/$id': typeof DashboardEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/become-contributor'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/admin/categories'
    | '/admin/contributors'
    | '/admin/posts'
    | '/admin/review'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/dashboard/new'
    | '/admin/'
    | '/dashboard/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-contributor'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/admin/categories'
    | '/admin/contributors'
    | '/admin/posts'
    | '/admin/review'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/dashboard/new'
    | '/admin'
    | '/dashboard/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/become-contributor'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/admin/categories'
    | '/admin/contributors'
    | '/admin/posts'
    | '/admin/review'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/dashboard/new'
    | '/admin/'
    | '/dashboard/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomeContributorRoute: typeof BecomeContributorRoute
  BlogRoute: typeof BlogRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardEditIdRoute: typeof DashboardEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-contributor': {
      id: '/become-contributor'
      path: '/become-contributor'
      fullPath: '/become-contributor'
      preLoaderRoute: typeof BecomeContributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contributors': {
      id: '/admin/contributors'
      path: '/contributors'
      fullPath: '/admin/contributors'
      preLoaderRoute: typeof AdminContributorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/edit/$id': {
      id: '/dashboard/edit/$id'
      path: '/dashboard/edit/$id'
      fullPath: '/dashboard/edit/$id'
      preLoaderRoute: typeof DashboardEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContributorsRoute: typeof AdminContributorsRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContributorsRoute: AdminContributorsRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeContributorRoute: BecomeContributorRoute,
  BlogRoute: BlogRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardEditIdRoute: DashboardEditIdRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
