import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createFileRoute } from "@tanstack/react-router";
import { PublicLayout } from "@/components/PublicLayout";
export const Route = createFileRoute("/about")({
    component: AboutPage,
});
function AboutPage() {
    return (_jsx(PublicLayout, { children: _jsx("div", { className: "page-shell section-space max-w-4xl", children: _jsxs("div", { className: "editorial-panel rounded-[2rem] px-6 py-10 md:px-10 md:py-12", children: [_jsx("span", { className: "section-kicker", children: "About us" }), _jsx("h1", { className: "mt-3 font-display text-4xl leading-tight md:text-6xl", children: "A publication that believes Nepal's story belongs first to Nepalis." }), _jsxs("div", { className: "prose-editorial mt-8 max-w-none", children: [_jsx("p", { children: "Hamro Katha - \"our story\" - was started with a simple idea: the country deserves storytelling that comes from the inside. Travel writing without the tourist gaze. Cultural essays that do not romanticize. Business reporting that takes farmers and shopkeepers as seriously as tech founders." }), _jsx("h2", { children: "What we publish" }), _jsx("p", { children: "Long reads on the things that matter - agriculture, climate, culture, entrepreneurship, daily life, and the unfamous corners of Nepal. We publish in English to reach a wider audience, but we welcome stories translated from Nepali, Maithili, Newari, and other languages." }), _jsx("h2", { children: "Who writes for us" }), _jsx("p", { children: "Anyone who has something honest and well-told to say. Nepali residents, diaspora writers, foreign correspondents who have earned the right to write about Nepal - all welcome. We review every submission carefully and give real editorial feedback." }), _jsx("h2", { children: "How we stay independent" }), _jsx("p", { children: "We are community-funded and ad-supported. No single outlet, sponsor, or party shapes our editorial agenda. Featured posts and partnerships, when we add them, will always be marked clearly." })] })] }) }) }));
}
